fix #11 ajustando relatorio de respostas
practice-uffs/forms pull request #12
Opened 2022-03-28 15:00 UTC by zorteaadriano

Como descrito na issue: #11, foi feito o tratamento para listar todas respostas de um relatório, incluindo também um botão de baixar todas as respostas do formulário em CSV, mantendo a opção de baixar individualmente caso a pergunta seja um select. Foi adicionado o texto '(Desativada)' para perguntas que não estejam mais exibindo para o usuário responder, podendo ser a versão anterior de uma pergunta ou simplesmente uma pergunta que foi removida mesmo que já haviam respostas.

Levei um tempo a mais por percebi que não estava listando perguntas sem respostas, aí tive que alterar isso também para manter o estilo de visualização, onde perguntas novas exibem ''Nenhuma resposta ainda".

Nessa imagem dá pra ter uma noção de como ficou, havia uma pergunta com duas respostas e foi inserido um select com duas opções, e depois inserido outra pergunta ali no meio delas que ficou sem nenhuma resposta.

![image](https://user-images.githubusercontent.com/74692811/160431091-504e45d2-9cee-4233-8659-7101230648e0.png)

2022-03-29 11:33 UTC, alissonpeloso commented
Quando apaga uma pergunta do tipo select, ele não avisa que tá desativada né? Acho que essa tag também precisaria ficar mais destacada. Poderia ser algo assim: 

![image](https://user-images.githubusercontent.com/51202705/160602238-1c81d347-a96c-458b-bd6f-80709a5bca04.png)

mas escrito "desativada".

2022-03-29 11:34 UTC, alissonpeloso commented
Ao baixar as respostas, quando tem uma pergunta de select, ele retorna o id do select, não teria como retornar realmente o valor?

2022-03-29 11:35 UTC, alissonpeloso requested changes
Tá no caminho certo, a implementação tá massa. Acho que só tenta arrumar as coisas que falei no comentário, qualquer coisa me chama.

2022-03-30 17:44 UTC, zorteaadriano commented
@alissonpeloso 
ficou assim, tanto pro gráfico quanto pras outras perguntas

![image](https://user-images.githubusercontent.com/74692811/160898204-80686d53-f8fa-4948-baaf-4daa5515cb20.png)

2022-03-31 12:55 UTC, merged