1
practice-uffs/forms pull request #5
Opened 2022-02-15 13:11 UTC by zorteaadriano

O menu para as telas menores ficou seguindo a mesma ideia do mural, abaixo tem um exemplo de visualização com os itens do menu, mas mantendo a foto do usuário quando logado à direita.
![image](https://user-images.githubusercontent.com/74692811/153953496-809df5c8-374d-4dfb-813b-4b2c34528c3a.png)

Já o problema com os formulários salvos sem conteúdo, a sugestão foi criar um botão de exclusão além de definir um título automático para o formulário no momento da criação para ter um controle visual melhor. Tendo em vista que foi uma solução mais simples para não exigir tanta alteração no formulário, que está salvando tudo automaticamente à cada alteração nos inputs.

Já na página de criação/edição do formulário, acabei alterando alguns tamanhos para ter mais responsividade, exemplo:
![image](https://user-images.githubusercontent.com/74692811/153961000-7207b429-f703-490b-a098-9750192b1643.png)

2022-02-15 21:44 UTC, CleissonVieira requested changes
Show, já testei na minha máquina e ficou legal, apenas não testei o botão de excluir
Porém, peço que teste, pois caso usuários respondam ao questionário e depois o mesmo é excluído isso não vai gerar erro? As respostas não estarão vinculadas ao questionário?

 Será que não conseguimos automatizar para se acaso o usuário saia do questionário sem clicar em um botão "Salvar" então o mesmo recebe um drop (deletado via código)? Caso clique no botão salvar então pula a etapa de dar o drop e salva normalmente.

2022-03-07 14:50 UTC, zorteaadriano commented
Oi @alissonpeloso então, agora com esse commit o tratamento das exclusões ficou da seguinte forma:

-Ao criar um formulário e não preencher nada, ele será excluído ao acessar a página de listagem.
-Ao preencher somente a pergunta, o título do formulário é preenchido automaticamente seguindo o padrão 'Formulário ID'.
-Existe ainda a opção de clicar em cancelar na tela de edição, ou remover na tela de listagem, ambos com confirmação.
-A exclusão do formulário está tratando remoção de respostas já enviadas.

2022-03-08 01:02 UTC, zorteaadriano commented
@alissonpeloso, acabei fazendo outro commit pra incluir no mesmo PR o código pra issue 3, que era só aquela mensagem de retorno que debatemos na última reunião, mas tem mais arquivos inclusos no commit pois pra rodar o projeto ele atualizou esses arquivos do livewire, agora precisei comitar eles pra não precisar refazer o processo, está ok fazer isso?

2022-03-08 10:44 UTC, alissonpeloso commented
> @alissonpeloso, acabei fazendo outro commit pra incluir no mesmo PR o código pra issue 3, que era só aquela mensagem de retorno que debatemos na última reunião, mas tem mais arquivos inclusos no commit pois pra rodar o projeto ele atualizou esses arquivos do livewire, agora precisei comitar eles pra não precisar refazer o processo, está ok fazer isso?

Acredito que sim, pois não havia dado o merge ainda

2022-03-08 11:00 UTC, alissonpeloso requested changes
Teria que ver para remover esses arquivos que ficam no gitignore (app.css, app.js, etc), eles não devem vir para o git.

Vi alguns problemas de layout no mobile, então vou criar outra tarefa pra ajustar essa parte.

2022-03-08 11:00 UTC, alissonpeloso commented on app/Http/Livewire/Form/Edit.php
> +        // $this->form->user_questions
Acredito que possa apagar esse comentário

2022-03-08 11:17 UTC, merged