Feat: novos ajustes no tema e add icone Form #6
practice-uffs/forms pull request #7
Opened 2022-03-07 04:44 UTC by CleissonVieira

Fix: #6 

Alterei os ícones e realizei alguns ajustes de corres.
Porém, encontrei muito código do próprio mural V1. 
Possivelmente é cópia do mesmo.

Acredito que seria interessante uma tarefa para limpar o Form de código que não é utilizado e padronizar o tema.
Assim como atualizar a branch Dev para organizar o fluxo e novos PR serem feitos para Dev

![image](https://user-images.githubusercontent.com/29258164/156969208-aff1678b-f82e-4864-9363-3ef4ee3d2c41.png)
![image](https://user-images.githubusercontent.com/29258164/156969243-cc75daf6-eac8-4bb9-a93d-06d5a1be1d4d.png)

2022-03-07 11:32 UTC, alissonpeloso commented
@CleissonVieira , na versão pra mobile ele não tá pegando a nova logo:

![image](https://user-images.githubusercontent.com/51202705/157023286-76279c63-0454-454c-bbdc-c574d4516b05.png)

2022-03-07 11:32 UTC, alissonpeloso requested changes
Corrigir logo no modo mobile

2022-03-07 11:39 UTC, alissonpeloso commented
Tarefa sobre os códigos reutilizados: [LINK](https://github.com/practice-uffs/forms/issues/8)

2022-03-08 06:48 UTC, CleissonVieira commented
@alissonpeloso realizei os ajustes e já dei merge com a branch 1 do Adriano para não dar conflito, sugiro testar e dar merge na dele para verificar se está ok a implementação

2022-03-08 11:15 UTC, alissonpeloso commented
Lembra de fazer os PRs para a `dev`

2022-03-08 11:17 UTC, merged

2022-03-08 11:31 UTC, alissonpeloso commented
@CleissonVieira, na próxima, não faz pull da branch de outra pessoa sem que ela esteja aceita.